### ISSUE TITLE
8.1.0 crashing on vercel

### ISSUE THREAD

**Issue by nervetattoo** [sanity-io/get-it#107]
Just had deployments starting to crash on vercel after get-it versions for sanity packages were bumped to 8.10 from 8.0.11
I confirmed the break to be in this version by overriding just get-it back to 8.0.11.
Here's the stack trace from the function failure:

```
TypeError: Right-hand side of 'instanceof' is not an object
    at (../../node_modules/.pnpm/get-it@8.1.0/node_modules/get-it/dist/index.browser.js:185:0)
    at (../../node_modules/.pnpm/get-it@8.1.0/node_modules/get-it/dist/index.browser.js:283:0)
    at (../../node_modules/.pnpm/get-it@8.1.0/node_modules/get-it/dist/index.browser.js:67:0)
    at (../../node_modules/.pnpm/get-it@8.1.0/node_modules/get-it/dist/index.browser.js:33:0)
    at (../../node_modules/.pnpm/get-it@8.1.0/node_modules/get-it/dist/middleware.browser.js:255:0)
    at (../../node_modules/.pnpm/rxjs@7.8.0/node_modules/rxjs/dist/cjs/internal/Observable.js:41:0)
    at (../../node_modules/.pnpm/rxjs@7.8.0/node_modules/rxjs/dist/cjs/internal/Observable.js:35:0)
    at (../../node_modules/.pnpm/rxjs@7.8.0/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:0)
    at (../../node_modules/.pnpm/rxjs@7.8.0/node_modules/rxjs/dist/cjs/internal/Observable.js:26:0)
    at (../../node_modules/.pnpm/@sanity+client@5.3.2/node_modules/@sanity/client/dist/index.browser.js:812:0)
```

**Comment by rexxars** [comment]
Thanks for reporting! Should be fixed in [v8.1.1](https://github.com/sanity-io/get-it/releases/tag/v8.1.1)
